### ISSUE TITLE
Subjects have wrong size

### ISSUE THREAD

**Issue by keijokorhonen** [keijokorhonen/mcnutty-website#1]
When hovered over the groups, the subjects are in the wrong size.

**Comment by devinmcnulty** [comment]
I think I fixed, check it out

**Comment by keijokorhonen** [comment]
Seems like the CSS is broken for me on both Chrome and Firefox
![](http://i.imgur.com/AhRDdRe.png)

**Comment by devinmcnulty** [comment]
Nope looks great ;)

**Comment by devinmcnulty** [comment]
Should be fixed

**Comment by keijokorhonen** [comment]
Alright worked in Chrome and Safari, but Firefox still had an issue so I fixed it
